---
title: "Afghan Chickpea Curry"
categories: 
  - veggie
---

::: column-page-right
Chickpeas and lentils come together to make a delicious meaty curry. *Serves 4 as a main, 6 as a side.*
:::

::: column-margin
## Ingredients

-   3 tbsp butter
-   1 cinnamon stick
-   4-6 curry leaves
-   2 shallots (or 1 onion), finely chopped
-   3 garlic cloves, minced
-   Thumb of ginger, minced
-   120g red lentils
-   1 litre chicken (or vegetable) stock
-   Salt and pepper
-   2 jars of chickpeas, drained
-   1/4 tsp baking powder
-   1 tbsp coriander powder
-   1 tbsp cumin powder
-   2 tsp turmeric powder
-   2 tsp garam masala
:::

::: column-body
## Method

-   Melt the butter in over medium high heat. Add the cinnamon and curry leaves, toast for 30 seconds. Fry the onion until translucent, adding ginger and garlic half way.
-   Fry off the spices (coriander, cumin, turmeric and garam masala) for 30 seconds. Add the lentils and stir to coat in the spices.
-   Pour in the stock with a turn of salt. Lower the heat and simmer for 15 minutes with the lid on.
-   Add the chickpeas and baking soda. Bring back to a simmer again for 30 minutes with the lid. Simmer for a further 5-10 minutes without the lid to thicken to the desired consistency.
-   Serve with rice and/or flatbreads. Top with fresh coriander.

*Inspiration:* [Recipe Tin Eats](https://www.recipetineats.com/melting-afghani-chickpea-curry/)
:::
