---
title: "Dal Makhani"
categories: 
  - veggie
  - main
  - side
---

::: column-page-right
Dishoom's famous dal but quickly (ish!). Punjabi comfort food! *Serves 3 as a main, 4 as a side.*
:::

::: column-margin
## Ingredients

-   2 cans black lentils (400g) \[urad dal\]
-   2 generous knobs of butter
-   1/2 a white onion
-   5 garlic cloves, finely chopped
-   1 inch of ginger, finely chopped
-   1 red chilli, finely chopped
-   2 tbsp of tomato puree
-   3 tsp garam masala
-   2 tsp coriander
-   1 tsp cumin
-   1/2 tsp chilli powder
-   Splash of double/whipping cream
-   Salt and pepper
:::

::: column-body
## Method

-   Boil the lentils for 1 hour in the liquid from the tin and a little water.

-   Heat a large knob of butter in a saucepan, saute onion until translucent, then add most of the chilli (save a little for topping), garlic and ginger for a couple of minutes.

-   Add dry spices and fry until fragrant before adding the tomato paste and drained lentils.

-   Cover the lentils with water and bring to the boil. Then simmer on a low heat with the lid on for 2 hours. Check regularly that there is enough water and stir to prevent the dal sticking to the bottom of the pan.

-   Use a stick blender to break up some of the lentils, but leave some lentils intact. Finish with a splash of cream and another knob of butter.

-   Serve with rice of naan bread, coriander and the remaining diced chilli.

*Inspiration: Dishoom*
:::
