---
title: "Tomato Butter Bean Stew"
categories: 
  - veggie
  - main
---

::: column-page-right
A tasty, hearty bean stew! *Serves 4.*
:::

::: column-margin
## Ingredients

-   Olive oil
-   1 small red onion, finely diced
-   Salt
-   4 cloves of garlic, finely sliced
-   Pinch of chilli flakes
-   1 tbsp oregano
-   Generous grind of black pepper
-   1 tbsp tomato puree
-   200g cherry tomatoes, halved
-   1 can chopped tomatoes
-   Pinch of sugar
-   Half a stock cube
-   2 can butter beans, incl. liquid
-   Squeeze of lemon
-   Baguette
:::

::: column-body
## Method

-   Sweat down the diced red onion in some olive oil and a grind of salt, until translucent, about 5 minutes.
-   Saute garlic for 1 minute, before frying off chilli, oregano, black pepper and tomato paste.
-   Add both cherry and chopped tomatoes, with a pinch of sugar and half a stock cube. Bring to a simmer for 10 minutes.
-   Pour in butter beans along with the liquid from the cans and a squeeze of lemon juice. Simmer gently for another 10 minutes, adding water as necessary to achieve desired consistency.
-   Adjust seasoning to taste and serve with fresh crusty baguette.

### Possible additions

-   A few handfuls of spinach.
-   Sliced pieces of a good quality sausage.
:::
