project:
  type: website
  output-dir: docs

website:
  title: "Cookbook"
  navbar:
    search: true
    left:
      - href: index.qmd
        text: Recipes
      - about.qmd

format:
  html:
    theme: minty
    css: styles.css
    toc: false

editor: visual
